name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message qui sera affiché lors du premier numéro des utilisateurs'
        pr-message: 'Message qui sera affiché lors de la première demande d extraction des utilisateurs'
